{{ if .Values.psp.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: robot-shop-{{ .Values.sandboxID }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: robot-shop-{{ .Values.sandboxID }}
subjects:
- kind: ServiceAccount
  name: robot-shop-{{ .Values.sandboxID }}
  namespace: robot-shop-{{ .Values.sandboxID }}
{{ end }}
