{{ if .Values.psp.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: robot-shop-{{ .Values.sandboxID }}
rules:
- apiGroups:
  - policy
  resourceNames:
  - robot-shop
  resources:
  - podsecuritypolicies
  verbs:
  - use
{{ end }}
