# dispatch just listens to a message queue
# it does not expose any ports
apiVersion: v1
kind: Service
metadata:
  name: dispatch-{{ .Values.sandboxID }}
  labels:
    service: dispatch-{{ .Values.sandboxID }}
spec:
  clusterIP: None
  ports:
  - name: headless
    port: 55555
    targetPort: 0
  selector:
    service: dispatch-{{ .Values.sandboxID }}
