apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-{{ .Values.sandboxID }}
  labels:
    service: payment-{{ .Values.sandboxID }}
    stage: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      service: payment-{{ .Values.sandboxID }}
      stage: prod
  template:
    metadata:
      labels:
        service: payment-{{ .Values.sandboxID }}
        stage: prod
    spec:
      {{ if .Values.psp.enabled }}
      serviceAccountName: robot-shop-{{ .Values.sandboxID }}
      {{ end }}
      containers:
      - name: payment-{{ .Values.sandboxID }}
        image: {{ .Values.image.repo }}/rs-payment:{{ .Values.image.version }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        # agent networking access
        env:
          - name: INSTANA_AGENT_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          {{- if .Values.payment.gateway }}
          - name: PAYMENT_GATEWAY
            value: {{ .Values.payment.gateway }}
          {{- end }}
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 50Mi
      restartPolicy: Always
