apiVersion: v1
kind: Service
metadata:
  labels:
    service: redis-{{ .Values.sandboxID }}
  name: redis-{{ .Values.sandboxID }}
spec:
  ports:
  - name: redis-{{ .Values.sandboxID }}
    port: 6379
    targetPort: 6379
  selector:
    service: redis-{{ .Values.sandboxID }}
