apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    service: redis-{{ .Values.sandboxID }}
  name: redis-{{ .Values.sandboxID }}
spec:
  replicas: 1
  selector:
    matchLabels:
      service: redis-{{ .Values.sandboxID }}
  serviceName: redis-{{ .Values.sandboxID }}
  template:
    metadata:
      labels:
        service: redis-{{ .Values.sandboxID }}
    spec:
      {{ if .Values.psp.enabled }}
      serviceAccountName: robot-shop-{{ .Values.sandboxID }}
      {{ end }}
      containers:
      - name: redis-{{ .Values.sandboxID }}
        image: redis:4.0.6
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 6379
        volumeMounts:
          - name: data-{{ .Values.sandboxID }}
            mountPath: /mnt/redis
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 50Mi
      restartPolicy: Always
  volumeClaimTemplates:
    - metadata:
        name: data-{{ .Values.sandboxID }}
      spec:
        accessModes: [ "ReadWriteOnce" ]
        {{ if not .Values.openshift }}
        storageClassName: {{ .Values.redis.storageClassName }}
        volumeMode: Filesystem
        {{ end }}
        resources:
          requests:
            storage: 1Gi

