apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping-{{ .Values.sandboxID }}
  labels:
    service: shipping-{{ .Values.sandboxID }}
spec:
  replicas: 1
  selector:
    matchLabels:
      service: shipping-{{ .Values.sandboxID }}
  template:
    metadata:
      labels:
        service: shipping-{{ .Values.sandboxID }}
    spec:
      {{ if .Values.psp.enabled }}
      serviceAccountName: robot-shop-{{ .Values.sandboxID }}
      {{ end }}
      containers:
      - name: shipping-{{ .Values.sandboxID }}
        image: {{ .Values.image.repo }}/rs-shipping:{{ .Values.image.version }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 8080
        # it's Java it needs lots of memory
        resources:
          limits:
            cpu: 200m
            memory: 1000Mi
          requests:
            cpu: 100m
            memory: 500Mi
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 30
          successThreshold: 1
      restartPolicy: Always
