apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: files
  name: files
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: guacamole
  name: guacamole
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: guacamole
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        # io.kompose.network/guacnetwork-compose: "true"
        io.kompose.service: guacamole
    spec:
      containers:
        - env:
            - name: GUACAMOLE_HOME
              value: /home/guacamole/.guacamole
            - name: GUACD_HOSTNAME
              value: guacd
            - name: GUACD_PORT
              value: "4822"
          image: 'qualihub/qualix_guacamole:4.0.0.400'
          securityContext:
            runAsUser: 0
          name: guacamole
          ports:
            - containerPort: 8080
            - containerPort: 8443
          resources: {}
          volumeMounts:
            - mountPath: /opt/guacamole/files
              name: files
      hostname: guacamole
      restartPolicy: Always
      volumes:
        - name: files
          persistentVolumeClaim:
            claimName: files

---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: guacd
  name: guacd
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: guacd
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        # io.kompose.network/guacnetwork-compose: "true"
        io.kompose.service: guacd
    spec:
      containers:
        - env:
            - name: GUACD_LOG_LEVEL
              value: debug
          image: 'qualihub/qualix_guacd:4.0.0.400'
          name: guacd
          ports:
            - containerPort: 4822
          resources: {}
          volumeMounts:
            - mountPath: /opt/guacamole/files
              name: files
      hostname: guacd
      restartPolicy: Always
      volumes:
        - name: files
          persistentVolumeClaim:
            claimName: files
